<a href="https://colab.research.google.com/github/ChaceXYang/data-analysis-practice/blob/main/NumPyNoteBook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Complete Python NumPy Tutorial (1)
>*by Keith Galli*
> 📅 听课日期：2026-03-23
> 🎯 本节主题：NumPy 库的核心原理与基本操作

---

## 一、NumPy 是什么？

NumPy（Numerical Python）是 Python 中用于科学计算的**基础核心库**。

- NumPy 是一个**多维数组库（Multidimensional Array Library）**
- 可以存储并操作：一维数组、二维数组、三维数组、四维数组……以此类推
- 它是许多主流数据科学库的**底层基础**，例如：
  - **Pandas**：几乎完全建立在 NumPy 之上
  - **SciPy**：科学计算扩展库（比 NumPy 数学功能更丰富）
  - **机器学习框架**（TensorFlow、PyTorch 等的 Tensor 概念与 NumPy 高度相似）

---

## 二、为什么用 NumPy 而不用列表（List）？——性能原理

这是本节课最重要的**底层原理**部分，理解了它才能真正理解 NumPy 的价值。

### 2.1 原因一：NumPy 使用固定类型（Fixed Types）

#### Python List 存储整数的方式

Python 列表使用内置的 `int` 类型，存储一个整数需要记录**四项信息**：

| 信息项 | 占用空间 |
|--------|----------|
| 对象值（Object Value）| ~8 字节（long 类型）|
| 对象类型（Object Type）| ~8 字节 |
| 引用计数（Reference Count）| ~8 字节 |
| 整数大小（Size）| ~4 字节 |

> ➡️ 仅仅存储**一个整数**，List 就需要消耗约 **28+ 字节**

#### NumPy 存储整数的方式

NumPy 默认将整数存储为 `int32`，即 **4 字节（32 位）**：

```python
# 默认 int32，占 4 字节
a = np.array([1, 2, 3])

# 可手动指定更小的类型以节省内存
a = np.array([1, 2, 3], dtype='int16')  # 2 字节
a = np.array([1, 2, 3], dtype='int8')   # 1 字节
```

> ➡️ **结论**：NumPy 占用内存更少 → 读取更快

---

### 2.2 原因二：无需类型检查（No Type Checking）

- Python List 可以混合存储不同类型（整数、浮点、字符串、布尔……）
- 因此在遍历列表时，**每个元素都需要检查其类型**，非常耗时
- NumPy 数组中的元素类型是**固定统一的**
- 遍历时**完全不需要类型检查** → 速度更快

---

### 2.3 原因三：连续内存（Contiguous Memory）

这是 NumPy 速度快的最关键原因之一。

#### Python List 的内存布局（分散）

```
内存地址:  [A]  [ ]  [B]  [ ]  [ ]  [C]  [ ]  [D] ...
```
- List 本身只存储**指针**（pointers），指向散落在内存各处的实际数据
- 访问数据时需要"跳来跳去"，效率低

#### NumPy Array 的内存布局（连续）

```
内存地址:  [1]  [2]  [3]  [4]  [5]  [6]  [7]  [8] （紧密相邻）
```
- NumPy 数组的所有元素在内存中**紧挨在一起**
- 只需记录：起始位置 + 总大小 + 数据类型

#### 连续内存的两大好处：

**① SIMD 向量化处理**

- CPU 拥有 **SIMD（Single Instruction Multiple Data，单指令多数据）** 处理单元
- 当内存连续时，可以**一条指令同时处理多个数据**
- 例如：对8个数求和，不是一个一个加，而是可以并行一次性完成

**② 更有效地利用 CPU 缓存（Cache）**

- CPU 缓存是比内存更快的存储区域
- 内存连续时，加载一批数据后可以把所有相关数据保留在缓存中，不需要反复从内存读取
- List 的数据分散，缓存命中率低，需要频繁"回去内存取数据"，大幅降低速度

---

### 2.4 NumPy 和 List 的功能对比

| 操作 | Python List | NumPy Array |
|------|-------------|-------------|
| 插入 | ✅ | ✅ |
| 删除 | ✅ | ✅ |
| 追加 | ✅ | ✅ |
| 拼接 | ✅ | ✅ |
| **逐元素运算** | ❌（需手动循环）| ✅（直接支持）|
| **数学函数** | ❌ | ✅ |
| **多维数组** | 嵌套列表，不优雅 | ✅ 原生支持 |

**示例：逐元素乘法**

```python
# List 做不到直接乘法，需要循环
# NumPy 可以直接逐元素计算
a = np.array([1, 3, 5])
b = np.array([1, 2, 3])
print(a * b)  # 输出：[1, 6, 15]
```

---

## 三、NumPy 的应用场景

老师列举了以下常见应用：

1. **数学计算**：可作为 MATLAB 的替代品（SciPy 提供更多数学函数）
2. **数据可视化**：作为 Matplotlib 等绘图库的数据后端
3. **Pandas 的底层核心**：Pandas 的 DataFrame 依赖 NumPy
4. **游戏开发**：如用二维数组存储棋盘状态（老师举例：Connect 4 游戏）
5. **图像处理**：图片（如 PNG）可以用 NumPy 数组表示和处理
6. **机器学习**：Tensor（张量）的概念与 NumPy 高度相似，理解 NumPy 有助于学习 TensorFlow / PyTorch

---

## 四、安装与导入

### 安装

```bash
pip install numpy
# 如果 pip 不行，尝试：
pip3 install numpy
```

### 导入（约定俗成的别名）

```python
import numpy as np
```

> 💡 老师使用 **Jupyter Notebook** 演示代码，但任何编辑器都可以。

---

## 五、创建数组（Array 初始化）

### 5.1 一维数组

```python
a = np.array([1, 2, 3])
print(a)  # 输出：[1 2 3]
```

### 5.2 二维数组（列表嵌套列表）

```python
b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])
print(b)
# 输出：
# [[9. 8. 7.]
#  [6. 5. 4.]]
```

### 5.3 三维数组及更高维

```python
# 继续嵌套列表即可创建三维、四维……数组
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
```

---

## 六、数组的常用属性

### 6.1 维度数量：`.ndim`

```python
print(a.ndim)  # 输出：1（一维）
print(b.ndim)  # 输出：2（二维）
```

### 6.2 形状：`.shape`

```python
print(a.shape)  # 输出：(3,)         → 一维，有3个元素
print(b.shape)  # 输出：(2, 3)       → 2行3列
```

### 6.3 数据类型：`.dtype`

```python
print(a.dtype)  # 输出：int32（默认）
print(b.dtype)  # 输出：float64（因为是小数）
```

可以在创建数组时手动指定类型：

```python
a = np.array([1, 2, 3], dtype='int16')
print(a.dtype)  # 输出：int16
```

### 6.4 每个元素的字节数：`.itemsize`

```python
a = np.array([1, 2, 3], dtype='int32')
print(a.itemsize)  # 输出：4（字节）

a = np.array([1, 2, 3], dtype='int16')
print(a.itemsize)  # 输出：2（字节）

print(b.itemsize)  # float64 → 输出：8（字节）
```

> 📌 规律：int8=1字节，int16=2字节，int32=4字节，int64=8字节；float64=8字节

### 6.5 元素总数量：`.size`

```python
print(a.size)  # 输出：3（共3个元素）
```

### 6.6 数组总字节数：`.nbytes`

```python
# 方法一：手动计算
total = a.size * a.itemsize

# 方法二：直接获取
print(a.nbytes)
```

---

## 七、访问与修改数组元素（索引与切片）

### 7.1 访问特定元素

语法：`array[行索引, 列索引]`

```python
a = np.array([[1,  2,  3,  4,  5,  6,  7],
              [8,  9, 10, 11, 12, 13, 14]])

# 获取第2行第6列的元素（索引从0开始）
print(a[1, 5])   # 输出：13

# 负数索引：从末尾倒数
print(a[1, -2])  # 输出：13（-1是14，-2是13）
```

### 7.2 获取整行

语法：`array[行索引, :]`

```python
print(a[0, :])   # 获取第1行所有列
# 输出：[1 2 3 4 5 6 7]
```

### 7.3 获取整列

语法：`array[:, 列索引]`

```python
print(a[:, 2])   # 获取第3列所有行
# 输出：[3 10]
```

### 7.4 切片访问（带步长）

语法：`array[行, 起始:结束:步长]`（结束索引**不包含**，区间左闭右开）

```python
# 获取第1行中，从索引1到5（不含），每隔2个取一个
print(a[0, 1:6:2])  # 输出：[2 4 6]
# 即：索引1→2, 索引3→4, 索引5→6
```

也可以使用负步长（反向）：
```python
print(a[0, 5:0:-2])  # 从索引5反向取，步长-2
```

### 7.5 修改特定元素

```python
a[1, 5] = 20     # 将原来的13改为20
print(a)
```

### 7.6 修改整列

```python
# 将第3列（索引2）全部改为5
a[:, 2] = 5
print(a)
# 输出中第3列全是5

# 也可以用数组替换，但形状必须匹配
a[:, 2] = [1, 2]
```

---

## 八、三维数组的索引（重要技巧）

### 老师推荐方法：**由外向内（Work Outside In）**

```python
b = np.array([[[1,  2],
               [3,  4]],
              [[5,  6],
               [7,  8]]])

# 想获取元素 4：
# 第1步：选外层 → 第一个"大块" → b[0]
# 第2步：在这个大块里选行 → 第二行 → b[0][1] 或 b[0, 1]
# 第3步：在这行里选列 → 第二列 → b[0, 1, 1]
print(b[0, 1, 1])  # 输出：4
```

### 三维数组的切片

```python
# 获取两个大块中的第二行，所有列
print(b[:, 1, :])
# 输出：
# [[3 4]
#  [7 8]]
```

### 三维数组的替换

替换时形状必须与目标区域**完全一致**：

```python
# 获取 b[:, 1, :] 是 2×2 的区域
b[:, 1, :] = [[9, 9], [8, 8]]   # ✅ 形状匹配，成功
b[:, 1, :] = [[9, 9, 9], [8, 8]]  # ❌ 形状不匹配，报错
```

---

## 九、总结：核心知识速查表

| 属性/操作 | 代码 | 说明 |
|-----------|------|------|
| 创建一维数组 | `np.array([1,2,3])` | |
| 创建二维数组 | `np.array([[1,2],[3,4]])` | 列表嵌套 |
| 维度数 | `a.ndim` | 1D→1，2D→2 |
| 形状 | `a.shape` | (行, 列) |
| 数据类型 | `a.dtype` | int32, float64 等 |
| 每元素字节 | `a.itemsize` | int32→4，float64→8 |
| 元素总数 | `a.size` | |
| 总字节数 | `a.nbytes` | =size × itemsize |
| 取特定元素 | `a[行, 列]` | 索引从0开始 |
| 取整行 | `a[0, :]` | |
| 取整列 | `a[:, 2]` | |
| 切片+步长 | `a[0, 1:6:2]` | 起:止(不含):步长 |
| 修改元素 | `a[1, 5] = 20` | 直接赋值 |
| 修改整列 | `a[:, 2] = [1, 2]` | 形状要匹配 |
| 三维索引 | `b[0, 1, 1]` | 由外向内 |

---

## 十、为什么 NumPy 快——三大原因总结

```
NumPy 速度快的三大原因：
├── 1. 固定类型（Fixed Types）
│       → 每个元素占用字节少，内存读写更快
├── 2. 无类型检查（No Type Checking）
│       → 遍历时不用逐一判断元素类型
└── 3. 连续内存（Contiguous Memory）
        ├── SIMD 向量化：一条指令处理多个数据
        └── 高效缓存命中：数据紧凑，不用反复读取内存
```

---

> 📌 **老师建议**：通常不需要手动指定 dtype，但如果追求内存效率，尽量选择能"刚好容纳"你数据的最小类型。

In [ ]:
# Load in NumPy (remember to pip install numpy first)
import numpy as np

a = np.array([1,2,3],dtype='int16')#you can specify what type of it
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) #arrays within a array
print(b)
# Get Dimension
print(a.ndim)
# Get Shape
print(b.shape)
# Get Type
print(a.dtype)
# Get Size
print(a.itemsize)
# Get total size
print(a.nbytes)
# Get number of elements
print(a.size)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]
1
(2, 3)
int16
2
6
3


## Accessing/Changing specific elements, rows, columns, etc

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])# 2 dimension array
print(a)
print(a.shape)
# Get a specific element [r, c](row,column)
print(a[1,5])
# Get a specific row
print(a[0,:])
# Get a specific column
print(a[:, 2])
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:-1:2])
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## *3-d example

In [ ]:
import numpy as np
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Get specific element (work outside in)
b[0,1,1]
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)
b[:,1,:] = [[9,9,9],[8,8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Complete Python NumPy Tutorial (2)