<a href="https://colab.research.google.com/github/ChaceXYang/data-analysis-practice/blob/main/NumPyNoteBook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Complete Python NumPy Tutorial (1)
>*by Keith Galli*
> 📅 听课日期：2026-03-23
> 🎯 本节主题：NumPy 库的核心原理与基本操作

---

## 一、NumPy 是什么？

NumPy（Numerical Python）是 Python 中用于科学计算的**基础核心库**。

- NumPy 是一个**多维数组库（Multidimensional Array Library）**
- 可以存储并操作：一维数组、二维数组、三维数组、四维数组……以此类推
- 它是许多主流数据科学库的**底层基础**，例如：
  - **Pandas**：几乎完全建立在 NumPy 之上
  - **SciPy**：科学计算扩展库（比 NumPy 数学功能更丰富）
  - **机器学习框架**（TensorFlow、PyTorch 等的 Tensor 概念与 NumPy 高度相似）

---

## 二、为什么用 NumPy 而不用列表（List）？——性能原理

这是本节课最重要的**底层原理**部分，理解了它才能真正理解 NumPy 的价值。

### 2.1 原因一：NumPy 使用固定类型（Fixed Types）

#### Python List 存储整数的方式

Python 列表使用内置的 `int` 类型，存储一个整数需要记录**四项信息**：

| 信息项 | 占用空间 |
|--------|----------|
| 对象值（Object Value）| ~8 字节（long 类型）|
| 对象类型（Object Type）| ~8 字节 |
| 引用计数（Reference Count）| ~8 字节 |
| 整数大小（Size）| ~4 字节 |

> ➡️ 仅仅存储**一个整数**，List 就需要消耗约 **28+ 字节**

#### NumPy 存储整数的方式

NumPy 默认将整数存储为 `int32`，即 **4 字节（32 位）**：

```python
# 默认 int32，占 4 字节
a = np.array([1, 2, 3])

# 可手动指定更小的类型以节省内存
a = np.array([1, 2, 3], dtype='int16')  # 2 字节
a = np.array([1, 2, 3], dtype='int8')   # 1 字节
```

> ➡️ **结论**：NumPy 占用内存更少 → 读取更快

---

### 2.2 原因二：无需类型检查（No Type Checking）

- Python List 可以混合存储不同类型（整数、浮点、字符串、布尔……）
- 因此在遍历列表时，**每个元素都需要检查其类型**，非常耗时
- NumPy 数组中的元素类型是**固定统一的**
- 遍历时**完全不需要类型检查** → 速度更快

---

### 2.3 原因三：连续内存（Contiguous Memory）

这是 NumPy 速度快的最关键原因之一。

#### Python List 的内存布局（分散）

```
内存地址:  [A]  [ ]  [B]  [ ]  [ ]  [C]  [ ]  [D] ...
```
- List 本身只存储**指针**（pointers），指向散落在内存各处的实际数据
- 访问数据时需要"跳来跳去"，效率低

#### NumPy Array 的内存布局（连续）

```
内存地址:  [1]  [2]  [3]  [4]  [5]  [6]  [7]  [8] （紧密相邻）
```
- NumPy 数组的所有元素在内存中**紧挨在一起**
- 只需记录：起始位置 + 总大小 + 数据类型

#### 连续内存的两大好处：

**① SIMD 向量化处理**

- CPU 拥有 **SIMD（Single Instruction Multiple Data，单指令多数据）** 处理单元
- 当内存连续时，可以**一条指令同时处理多个数据**
- 例如：对8个数求和，不是一个一个加，而是可以并行一次性完成

**② 更有效地利用 CPU 缓存（Cache）**

- CPU 缓存是比内存更快的存储区域
- 内存连续时，加载一批数据后可以把所有相关数据保留在缓存中，不需要反复从内存读取
- List 的数据分散，缓存命中率低，需要频繁"回去内存取数据"，大幅降低速度

---

### 2.4 NumPy 和 List 的功能对比

| 操作 | Python List | NumPy Array |
|------|-------------|-------------|
| 插入 | ✅ | ✅ |
| 删除 | ✅ | ✅ |
| 追加 | ✅ | ✅ |
| 拼接 | ✅ | ✅ |
| **逐元素运算** | ❌（需手动循环）| ✅（直接支持）|
| **数学函数** | ❌ | ✅ |
| **多维数组** | 嵌套列表，不优雅 | ✅ 原生支持 |

**示例：逐元素乘法**

```python
# List 做不到直接乘法，需要循环
# NumPy 可以直接逐元素计算
a = np.array([1, 3, 5])
b = np.array([1, 2, 3])
print(a * b)  # 输出：[1, 6, 15]
```

---

## 三、NumPy 的应用场景

老师列举了以下常见应用：

1. **数学计算**：可作为 MATLAB 的替代品（SciPy 提供更多数学函数）
2. **数据可视化**：作为 Matplotlib 等绘图库的数据后端
3. **Pandas 的底层核心**：Pandas 的 DataFrame 依赖 NumPy
4. **游戏开发**：如用二维数组存储棋盘状态（老师举例：Connect 4 游戏）
5. **图像处理**：图片（如 PNG）可以用 NumPy 数组表示和处理
6. **机器学习**：Tensor（张量）的概念与 NumPy 高度相似，理解 NumPy 有助于学习 TensorFlow / PyTorch

---

## 四、安装与导入

### 安装

```bash
pip install numpy
# 如果 pip 不行，尝试：
pip3 install numpy
```

### 导入（约定俗成的别名）

```python
import numpy as np
```

> 💡 老师使用 **Jupyter Notebook** 演示代码，但任何编辑器都可以。

---

## 五、创建数组（Array 初始化）

### 5.1 一维数组

```python
a = np.array([1, 2, 3])
print(a)  # 输出：[1 2 3]
```

### 5.2 二维数组（列表嵌套列表）

```python
b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])
print(b)
# 输出：
# [[9. 8. 7.]
#  [6. 5. 4.]]
```

### 5.3 三维数组及更高维

```python
# 继续嵌套列表即可创建三维、四维……数组
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
```

---

## 六、数组的常用属性

### 6.1 维度数量：`.ndim`

```python
print(a.ndim)  # 输出：1（一维）
print(b.ndim)  # 输出：2（二维）
```

### 6.2 形状：`.shape`

```python
print(a.shape)  # 输出：(3,)         → 一维，有3个元素
print(b.shape)  # 输出：(2, 3)       → 2行3列
```

### 6.3 数据类型：`.dtype`

```python
print(a.dtype)  # 输出：int32（默认）
print(b.dtype)  # 输出：float64（因为是小数）
```

可以在创建数组时手动指定类型：

```python
a = np.array([1, 2, 3], dtype='int16')
print(a.dtype)  # 输出：int16
```

### 6.4 每个元素的字节数：`.itemsize`

```python
a = np.array([1, 2, 3], dtype='int32')
print(a.itemsize)  # 输出：4（字节）

a = np.array([1, 2, 3], dtype='int16')
print(a.itemsize)  # 输出：2（字节）

print(b.itemsize)  # float64 → 输出：8（字节）
```

> 📌 规律：int8=1字节，int16=2字节，int32=4字节，int64=8字节；float64=8字节

### 6.5 元素总数量：`.size`

```python
print(a.size)  # 输出：3（共3个元素）
```

### 6.6 数组总字节数：`.nbytes`

```python
# 方法一：手动计算
total = a.size * a.itemsize

# 方法二：直接获取
print(a.nbytes)
```

---

## 七、访问与修改数组元素（索引与切片）

### 7.1 访问特定元素

语法：`array[行索引, 列索引]`

```python
a = np.array([[1,  2,  3,  4,  5,  6,  7],
              [8,  9, 10, 11, 12, 13, 14]])

# 获取第2行第6列的元素（索引从0开始）
print(a[1, 5])   # 输出：13

# 负数索引：从末尾倒数
print(a[1, -2])  # 输出：13（-1是14，-2是13）
```

### 7.2 获取整行

语法：`array[行索引, :]`

```python
print(a[0, :])   # 获取第1行所有列
# 输出：[1 2 3 4 5 6 7]
```

### 7.3 获取整列

语法：`array[:, 列索引]`

```python
print(a[:, 2])   # 获取第3列所有行
# 输出：[3 10]
```

### 7.4 切片访问（带步长）

语法：`array[行, 起始:结束:步长]`（结束索引**不包含**，区间左闭右开）

```python
# 获取第1行中，从索引1到5（不含），每隔2个取一个
print(a[0, 1:6:2])  # 输出：[2 4 6]
# 即：索引1→2, 索引3→4, 索引5→6
```

也可以使用负步长（反向）：
```python
print(a[0, 5:0:-2])  # 从索引5反向取，步长-2
```

### 7.5 修改特定元素

```python
a[1, 5] = 20     # 将原来的13改为20
print(a)
```

### 7.6 修改整列

```python
# 将第3列（索引2）全部改为5
a[:, 2] = 5
print(a)
# 输出中第3列全是5

# 也可以用数组替换，但形状必须匹配
a[:, 2] = [1, 2]
```

---

## 八、三维数组的索引（重要技巧）

### 老师推荐方法：**由外向内（Work Outside In）**

```python
b = np.array([[[1,  2],
               [3,  4]],
              [[5,  6],
               [7,  8]]])

# 想获取元素 4：
# 第1步：选外层 → 第一个"大块" → b[0]
# 第2步：在这个大块里选行 → 第二行 → b[0][1] 或 b[0, 1]
# 第3步：在这行里选列 → 第二列 → b[0, 1, 1]
print(b[0, 1, 1])  # 输出：4
```

### 三维数组的切片

```python
# 获取两个大块中的第二行，所有列
print(b[:, 1, :])
# 输出：
# [[3 4]
#  [7 8]]
```

### 三维数组的替换

替换时形状必须与目标区域**完全一致**：

```python
# 获取 b[:, 1, :] 是 2×2 的区域
b[:, 1, :] = [[9, 9], [8, 8]]   # ✅ 形状匹配，成功
b[:, 1, :] = [[9, 9, 9], [8, 8]]  # ❌ 形状不匹配，报错
```

---

## 九、总结：核心知识速查表

| 属性/操作 | 代码 | 说明 |
|-----------|------|------|
| 创建一维数组 | `np.array([1,2,3])` | |
| 创建二维数组 | `np.array([[1,2],[3,4]])` | 列表嵌套 |
| 维度数 | `a.ndim` | 1D→1，2D→2 |
| 形状 | `a.shape` | (行, 列) |
| 数据类型 | `a.dtype` | int32, float64 等 |
| 每元素字节 | `a.itemsize` | int32→4，float64→8 |
| 元素总数 | `a.size` | |
| 总字节数 | `a.nbytes` | =size × itemsize |
| 取特定元素 | `a[行, 列]` | 索引从0开始 |
| 取整行 | `a[0, :]` | |
| 取整列 | `a[:, 2]` | |
| 切片+步长 | `a[0, 1:6:2]` | 起:止(不含):步长 |
| 修改元素 | `a[1, 5] = 20` | 直接赋值 |
| 修改整列 | `a[:, 2] = [1, 2]` | 形状要匹配 |
| 三维索引 | `b[0, 1, 1]` | 由外向内 |

---

## 十、为什么 NumPy 快——三大原因总结

```
NumPy 速度快的三大原因：
├── 1. 固定类型（Fixed Types）
│       → 每个元素占用字节少，内存读写更快
├── 2. 无类型检查（No Type Checking）
│       → 遍历时不用逐一判断元素类型
└── 3. 连续内存（Contiguous Memory）
        ├── SIMD 向量化：一条指令处理多个数据
        └── 高效缓存命中：数据紧凑，不用反复读取内存
```

---

> 📌 **老师建议**：通常不需要手动指定 dtype，但如果追求内存效率，尽量选择能"刚好容纳"你数据的最小类型。

In [ ]:
# Load in NumPy (remember to pip install numpy first)
import numpy as np

a = np.array([1,2,3],dtype='int16')#you can specify what type of it
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) #arrays within a array
print(b)
# Get Dimension
print(a.ndim)
# Get Shape
print(b.shape)
# Get Type
print(a.dtype)
# Get Size
print(a.itemsize)
# Get total size
print(a.size*a.itemsize)
print(a.nbytes)
# Get number of elements
print(a.size)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]
1
(2, 3)
int16
2
6
6
3


## Accessing/Changing specific elements, rows, columns, etc

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])# 2 dimension array
print(a)
print(a.shape)
# Get a specific element [r, c](row,column)
print(a[1,5])
# Get a specific row
print(a[0,:])#a的第一列
# Get a specific column
print(a[:, 2])
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:-1:2])
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## *3-d example

In [ ]:
import numpy as np
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Get specific element (work outside in)
print(b[0,1,1])
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)
# b[:,1,:] = [[9,9,9],[8,8]] is elligal

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Complete Python NumPy Tutorial (2)
>*by Keith Galli*
> 📅 听课日期：2026-03-25
> 🎯 本节主题：特殊数组初始化 / 数组拷贝 / 数学运算 / 线性代数 / 统计 / 数组重组 / 文件读取 / 布尔掩码与高级索引

> 📌 **说明**：本节为 NumPy 完整教程，前半部分（NumPy 原理 + 基础索引）已在上节笔记中详细记录，本份笔记**从特殊数组初始化开始**，重点整理新内容。

---

## 一、特殊数组的初始化

除了手动传入数据，NumPy 提供了多种快速生成特定内容数组的函数。

---

### 1.1 全零数组：`np.zeros()`

```python
# 一维：生成5个0
np.zeros(5)
# 输出：[0. 0. 0. 0. 0.]

# 二维：2行3列
np.zeros((2, 3))

# 三维：2×3×3
np.zeros((2, 3, 3))

# 四维
np.zeros((2, 3, 3, 2))
```

> 💡 默认数据类型是 `float64`，所以显示的是 `0.` 而非 `0`

---

### 1.2 全一数组：`np.ones()`

```python
np.ones((4, 2, 2))
# 生成一个4×2×2的全1数组

# 可以指定数据类型
np.ones((4, 2, 2), dtype='int32')
```

---

### 1.3 自定义填充值：`np.full()`

`np.full()` 接受两个参数：**形状** 和 **填充值**

```python
# 生成一个2×2的全99数组
np.full((2, 2), 99)
# 输出：
# [[99 99]
#  [99 99]]

# 指定数据类型为 float32
np.full((2, 2), 99, dtype='float32')
```

---

### 1.4 按已有数组形状填充：`np.full_like()`

如果想生成一个与某个已有数组**形状相同**的填充数组，用 `full_like` 更方便：

```python
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# 方法一：full_like（推荐，更简洁）
np.full_like(a, 4)

# 方法二：full + shape（等价，但繁琐）
np.full(a.shape, 4)
```

> 两者效果相同，`full_like` 直接传入数组，自动读取其 shape。

---

### 1.5 随机小数数组：`np.random.rand()`

生成 **0 到 1 之间** 的随机浮点数：

```python
# ⚠️ 注意：rand() 不接受 tuple，直接传整数
np.random.rand(4, 2)       # 4行2列
np.random.rand(4, 2, 3)    # 4×2×3 三维

# 如果想传入 shape 变量，用 random_sample
np.random.random_sample(a.shape)
```

> ⚠️ **常见错误**：`np.random.rand((4, 2))` 会报错，因为它不接受 tuple，要写成 `np.random.rand(4, 2)`

---

### 1.6 随机整数数组：`np.random.randint()`

```python
# 语法：np.random.randint(low, high, size=形状)

# 生成0到6（不含7）之间的随机整数，形状3×3
np.random.randint(7, size=(3, 3))

# 指定范围：4到6（不含7）
np.random.randint(4, 7, size=(3, 3))

# 也支持负数
np.random.randint(-3, 7, size=(3, 3))
```

> 💡 上界是**不包含**的（exclusive）：`randint(0, 7)` 最大取到 6

---

### 1.7 单位矩阵（Identity Matrix）：`np.identity()`

```python
np.identity(3)
# 输出：
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]
```

> 只需要一个参数（行/列数），因为单位矩阵天然是**方阵**

---

### 1.8 重复数组：`np.repeat()`

```python
arr = np.array([[1, 2, 3]])

# 沿 axis=0（行方向）重复3次
r1 = np.repeat(arr, 3, axis=0)
print(r1)
# 输出：
# [[1 2 3]
#  [1 2 3]
#  [1 2 3]]
```

> ⚠️ 注意：传入**一维向量**时，`axis` 参数可能不按预期工作。建议先将数组转为二维（如 `[[1,2,3]]`）再 repeat。

---

### 1.9 综合练习：用基础函数构建特定矩阵

**目标**：构建如下矩阵（外圈全1，中间3×3含一个9）

```
[[1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 9, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 1, 1, 1, 1]]
```

**解题思路**：

```python
# 第一步：创建5×5全1矩阵
output = np.ones((5, 5))

# 第二步：创建3×3全0矩阵
z = np.zeros((3, 3))

# 第三步：在中心位置填入9
z[1, 1] = 9

# 第四步：将z嵌入output的中间部分
# 行：第1到第3行（索引1到4，排除边缘）
# 列：第1到第3列（同上）
output[1:4, 1:4] = z
# 也可以用负索引写成：
output[1:-1, 1:-1] = z

print(output)
```

> 💡 **技巧**：`1:-1` 等价于"从第二个到倒数第二个"，更通用。

---

## 二、拷贝数组（非常重要！）

### ⚠️ 危险：直接赋值不是拷贝！

```python
a = np.array([1, 2, 3])
b = a           # ❌ b 只是 a 的"别名"，不是独立副本

b[0] = 100

print(b)  # [100, 2, 3]  ← 看起来正常
print(a)  # [100, 2, 3]  ← a 也被修改了！！！
```

**原因**：`b = a` 只是让变量 `b` 指向了和 `a` 相同的内存地址，并没有创建新的数据。修改 `b` 就是在修改 `a` 的内容。

---

### ✅ 正确做法：使用 `.copy()`

```python
a = np.array([1, 2, 3])
b = a.copy()    # ✅ 创建真正的独立副本

b[0] = 100

print(b)  # [100, 2, 3]
print(a)  # [1, 2, 3]   ← a 不受影响！
```

> 🔥 **这是初学者最容易踩的坑之一，务必牢记：NumPy 中赋值 ≠ 拷贝，需要用 `.copy()` 才能得到独立副本。**

---

## 三、数学运算

### 3.1 元素级（Element-wise）四则运算

```python
a = np.array([1, 2, 3, 4])

print(a + 2)    # [3, 4, 5, 6]     每个元素加2
print(a - 2)    # [-1, 0, 1, 2]    每个元素减2
print(a * 2)    # [2, 4, 6, 8]     每个元素乘2
print(a / 2)    # [0.5, 1., 1.5, 2.]  每个元素除2
```

### 3.2 复合赋值运算

```python
a += 2   # 等价于 a = a + 2，原地修改
print(a) # [3, 4, 5, 6]
```

### 3.3 两个数组之间的运算

```python
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

print(a + b)  # [2, 2, 4, 4]
```

### 3.4 幂运算

```python
print(a ** 2)  # [1, 4, 9, 16]
```

### 3.5 三角函数等数学函数

```python
print(np.sin(a))   # 对每个元素求正弦值
print(np.cos(a))   # 对每个元素求余弦值
```

> 💡 NumPy 提供了大量数学函数，可以对整个数组一次性操作，完整列表可查阅官方文档的 **Math Routines** 部分。

---

## 四、线性代数（Linear Algebra）

线性代数运算与普通逐元素运算不同，它处理的是**矩阵级别**的数学运算。

### 4.1 矩阵乘法：`np.matmul()`

> ⚠️ 直接用 `*` 是逐元素乘法，不是矩阵乘法！

```python
a = np.ones((2, 3))      # 2×3 全1矩阵
b = np.full((3, 2), 2)   # 3×2 全2矩阵

# 矩阵乘法要求：第一个矩阵的列数 == 第二个矩阵的行数
# 2×3 乘 3×2 → 结果是 2×2
result = np.matmul(a, b)
print(result)
# 输出：
# [[6. 6.]
#  [6. 6.]]
```

**维度不匹配时会报错**，例如 `matmul(2×3, 2×3)` 会失败。

---

### 4.2 行列式：`np.linalg.det()`

```python
c = np.identity(3)
print(np.linalg.det(c))  # 输出：1.0
# 单位矩阵的行列式为1，符合线性代数定理
```

---

### 4.3 其他线性代数函数（`np.linalg` 模块）

| 函数 | 用途 |
|------|------|
| `np.linalg.det(A)` | 行列式 |
| `np.linalg.inv(A)` | 逆矩阵 |
| `np.linalg.eig(A)` | 特征值和特征向量 |

> 💡 更多线性代数函数见 NumPy 官方文档 **linalg** 部分

---

## 五、统计函数

```python
stats = np.array([[1, 2, 3],
                  [4, 5, 6]])
```

### 5.1 最小值：`np.min()`

```python
np.min(stats)           # 整体最小值：1

np.min(stats, axis=0)   # 每列的最小值：[1, 2, 3]（沿行方向向下比较）
np.min(stats, axis=1)   # 每行的最小值：[1, 4]（沿列方向横向比较）
```

### 5.2 最大值：`np.max()`

```python
np.max(stats)           # 整体最大值：6

np.max(stats, axis=0)   # 每列的最大值：[4, 5, 6]
np.max(stats, axis=1)   # 每行的最大值：[3, 6]
```

### 5.3 求和：`np.sum()`

```python
np.sum(stats)           # 所有元素求和：21

np.sum(stats, axis=0)   # 每列求和：[5, 7, 9]（列方向）
np.sum(stats, axis=1)   # 每行求和：[6, 15]（行方向）
```

### axis 参数的理解

| axis 值 | 含义 | 记忆方式 |
|---------|------|----------|
| 不指定 | 对所有元素操作 | 整体 |
| `axis=0` | 沿**行方向**（↓ 向下）操作 | 压缩行，结果是按**列**的 |
| `axis=1` | 沿**列方向**（→ 横向）操作 | 压缩列，结果是按**行**的 |

---

## 六、数组重组

### 6.1 改变形状：`.reshape()`

要求：重塑前后**元素总数必须相同**。

```python
before = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
# before 是 2×4，共8个元素

after = before.reshape((8, 1))    # 8行1列
after = before.reshape((4, 2))    # 4行2列
after = before.reshape((2, 2, 2)) # 三维 2×2×2，共8个元素 ✅

# ❌ 以下会报错，因为 2×3=6 ≠ 8
after = before.reshape((2, 3))    # ValueError!
```

> 💡 **报错原因通常是**：新形状的元素总数与原数组不一致。

---

### 6.2 垂直堆叠：`np.vstack()`

将多个数组**上下拼接**（行数增加）：

```python
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])
# 输出：
# [[1, 2, 3, 4],
#  [5, 6, 7, 8]]

# 可以重复多次
np.vstack([v1, v2, v2, v2])
```

> ⚠️ 要求：每个数组的**列数必须相同**，否则报错。

---

### 6.3 水平堆叠：`np.hstack()`

将多个数组**左右拼接**（列数增加）：

```python
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])
# 将 h2 拼接到 h1 的右边
# 输出：2行6列的数组（4列1 + 2列0）
```

> ⚠️ 要求：每个数组的**行数必须相同**，否则报错。

---

## 七、从文件加载数据

### 7.1 从文本文件读取：`np.genfromtxt()`

适合读取以某个字符分隔的数据文件（如 CSV 格式）：

```python
# 读取逗号分隔的 data.txt 文件
file_data = np.genfromtxt('data.txt', delimiter=',')
print(file_data)
# 自动解析为 NumPy 数组，默认类型是 float64
```

---

### 7.2 转换数据类型：`.astype()`

读取进来的数据默认是 `float64`，如果需要整数类型：

```python
# ⚠️ 直接调用 astype 不会修改原变量，需要重新赋值
file_data = file_data.astype('int32')
print(file_data)
# 现在是整数格式
```

> 💡 `.astype()` 会**创建一个新副本**（因为 float64 和 int32 字节大小不同，无法原地转换），需要将结果重新赋给变量。

---

## 八、布尔掩码与高级索引

这是 NumPy 非常强大的特性，可以用条件表达式来筛选数据。

### 8.1 比较运算生成布尔数组

```python
file_data = np.array([[...]])  # 假设已加载数据

# 对每个元素判断是否 > 50，返回同形状的 True/False 数组
print(file_data > 50)
# 输出：
# [[False False False False True]
#  ...]
```

---

### 8.2 用布尔数组作为索引（布尔掩码）

```python
# 直接获取所有 > 50 的值（结果是一维数组）
print(file_data[file_data > 50])
# 输出：所有满足条件的元素值
```

---

### 8.3 用列表索引（花式索引）

```python
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 同时取第0、2、8个位置的元素
print(a[[0, 2, 8]])  # 输出：[1, 3, 9]
```

> 💡 这也是布尔掩码的底层原理：True 对应"取这个位置"，False 对应"跳过"。

---

### 8.4 `np.any()`：任意一个满足条件

```python
# axis=0：对每一列，检查是否有任意一行的值 > 50
np.any(file_data > 50, axis=0)
# 输出：[False, False, False, False, True, True, True, False, True, True, False, True]
# 表示哪些列中存在 > 50 的值

# axis=1：对每一行，检查是否有任意一列的值 > 50
np.any(file_data > 50, axis=1)
```

---

### 8.5 `np.all()`：全部满足条件

```python
# axis=0：对每一列，检查是否所有行的值都 > 50
np.all(file_data > 50, axis=0)
# 返回 True 的列更少，只有当该列所有元素都 > 50 才为 True
```

---

### 8.6 多条件组合（用 `&` 和 `~`）

> ⚠️ Python 中，NumPy 多条件**不能用 `and` / `or`**，必须用 `&`（与）、`|`（或）、`~`（非），且每个条件要用**括号**括起来。

```python
# 找出所有 > 50 且 < 100 的值
result = file_data[(file_data > 50) & (file_data < 100)]
print(result)

# 取反：不在 50~100 之间的值（~ 表示 NOT）
result = file_data[~((file_data > 50) & (file_data < 100))]
print(result)
```

---

## 九、高级索引综合练习（Quiz）

老师给出了一个测试题，考察综合索引能力：

**数组示例（6行5列）：**

```
[[ 1,  2,  3,  4,  5],
 [ 6,  7,  8,  9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25],
 [26, 27, 28, 29, 30]]
```

**题目1**：取第2、3行（索引1、2），前两列（索引0、1）

```python
a[1:3, 0:2]
```

**题目2**：同时取多行多列中的**特定组合**（对角线式取值）

```python
# 取第0、1、2、3行，对应第1、2、3、4列（配对取值）
a[[0, 1, 2, 3], [1, 2, 3, 4]]
# 即取：a[0,1], a[1,2], a[2,3], a[3,4]
```

**题目3**：取第0、4、5行，第3列及之后所有列

```python
a[[0, 4, 5], 3:]
# 或：a[[0, 4, 5], 3:5]
# 或：a[[0, 4, 5], [3, 4]]
```

---

## 十、全课总结：NumPy 知识体系速查

```
NumPy
├── 为什么用 NumPy？
│   ├── 固定类型 → 占内存少 → 读取快
│   ├── 无类型检查 → 遍历快
│   └── 连续内存 → SIMD并行 + 高效缓存
│
├── 创建数组
│   ├── np.array([...])           手动创建
│   ├── np.zeros(shape)           全0
│   ├── np.ones(shape)            全1
│   ├── np.full(shape, val)       自定义填充
│   ├── np.full_like(arr, val)    按已有数组形状填充
│   ├── np.random.rand(r, c)      随机小数[0,1)
│   ├── np.random.randint(lo,hi,size=)  随机整数
│   ├── np.identity(n)            单位矩阵
│   └── np.repeat(arr, n, axis)   重复数组
│
├── 数组属性
│   ├── .ndim       维度数
│   ├── .shape      形状 (行, 列)
│   ├── .dtype      数据类型
│   ├── .itemsize   每元素字节数
│   ├── .size       元素总数
│   └── .nbytes     总字节数
│
├── 索引与切片
│   ├── a[行, 列]                   取单个元素
│   ├── a[行, :]                    取整行
│   ├── a[:, 列]                    取整列
│   ├── a[行, 起:止:步]              切片+步长
│   ├── a[[r1,r2], [c1,c2]]         花式索引（配对取值）
│   └── 三维：由外向内 b[0, 1, 1]
│
├── 拷贝
│   └── b = a.copy()    ← 必须用 copy()，直接赋值是引用！
│
├── 数学运算
│   ├── +, -, *, /, **              元素级运算
│   ├── np.sin(), np.cos()          三角函数
│   └── np.matmul(A, B)             矩阵乘法
│
├── 线性代数（np.linalg）
│   ├── np.matmul(A, B)             矩阵乘法
│   ├── np.linalg.det(A)            行列式
│   ├── np.linalg.inv(A)            逆矩阵
│   └── np.linalg.eig(A)            特征值
│
├── 统计
│   ├── np.min(a, axis=)
│   ├── np.max(a, axis=)
│   └── np.sum(a, axis=)
│
├── 数组重组
│   ├── a.reshape(new_shape)        重塑形状（元素总数不变）
│   ├── np.vstack([a, b])           垂直堆叠（上下拼接）
│   └── np.hstack([a, b])           水平堆叠（左右拼接）
│
├── 文件操作
│   ├── np.genfromtxt('file', delimiter=',')  读取文件
│   └── arr.astype('int32')                   类型转换
│
└── 布尔掩码与高级索引
    ├── a[a > 50]                      条件筛选
    ├── np.any(a > 50, axis=)          任意满足
    ├── np.all(a > 50, axis=)          全部满足
    └── a[(a > 50) & (a < 100)]        多条件（用 & 和括号）
```

---

> 📌 **老师推荐**：不需要记住所有函数，重要的是知道"NumPy 能做这件事"，需要时再查文档即可。老师的完整代码已上传至 GitHub，可在视频描述中找到链接。

## Initializing Different Types of Arrays

In [7]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])# 2 dimension array
# All 0s matrix
print(np.zeros((5)))
print(np.zeros((2,3,3)))
# All 1s matrix
print(np.ones((4,2,2),dtype='int32'))
# Any other number
print(np.full((2,2),99))
# Any other number (full_like)
print(np.full_like(a,4))
# Random decimal numbers
print(np.random.rand(4,2))
print(np.random.rand(4,2,3))
# Random Integer values
print(np.random.randint(-4,8,size=(3,3)))
# The identity matrix
np.identity(5)
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[0.28366305 0.2965027 ]
 [0.1381481  0.03413934]
 [0.55625339 0.33940667]
 [0.71708309 0.8019973 ]]
[[[0.25671459 0.06790673 0.16838713]
  [0.12817719 0.61278368 0.74417079]]

 [[0.47579722 0.38869399 0.8631536 ]
  [0.7540311  0.7107455  0.84589137]]

 [[0.57748126 0.46540395 0.34066593]
  [0.68074484 0.23422004 0.42408783]]

 [[0.43523867 0.28901975 0.47227096]
  [0.40384534 0.66462158 0.27920658]]]
[[-2  4  6]
 [ 4  5 -3]
 [ 0 -2  5]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [4]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [12]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
b = np.array([1,0,1,0])
print(a + b)
print(a ** 2)
# Take the sin
np.cos(a)

# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[2 2 4 4]
[ 1  4  9 16]


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [13]:
import numpy as np

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

# Find the determinant
c = np.identity(3)
np.linalg.det(c)

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


np.float64(1.0)

### Statistics

In [15]:
import numpy as np
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats, axis=0))

[[1 2 3]
 [4 5 6]]
1


## Reorganizing Arrays

In [16]:
import numpy as np
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [20]:
import numpy as np
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))

# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


## Miscellaneous
### Load Data from File

In [21]:
import numpy as np
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [22]:
import numpy as np
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')

print((~((filedata > 50) & (filedata < 100))))

[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
